# products.py
products_list = [
    {
        id: 1,
        refa: "REF: 102.002.0020",
        name: "Bowie Dick Test Pack - Economic",
        file:"bowi.pdf",
        desciption: "Used for daily monitoring of pre-vacuum steam sterilizer. Based upon the Bowie Dick test result the steam sterilizer is released for usage during the day",
        image: "one.png",
        characteristics:["✦ Fulfill requirements of EN 285 and ISO 17665 ",
        "✦ Conform to ISO 11140 - 4 Type 2 / EN 867 - 4 class B (EU standard 7 kilo)",
        "✦ Easy to interpret,  Easy to document ",
        "✦ Independently tested to show performance similar to original pack ",
        "✦ Clear blue - violet color change  Non-Toxic / Lead Free",
        "✦ Dimensions: 123 x 123 x 16 mm ",
    },
    {
        id: 2,
        refa: "REF: 102.100.0100",
        name:"Bowie Dick Test Pack - Mini",
        file:"bowi-mini.pdf",
        desciption:"Recommended for daily monitoring of pre-vacuum steam sterilizer and bench-top steam sterilizers(Class B). Based upon the Bowie Dick test result the steam sterilizer is released for usage duringthe day.",
        image:"two.png",
         characteristics:["✦ Fulfill requirements of EN 285 and ISO 17665 ",
        "✦ Conform to ISO 11140 - 4 Type 2 / Performance similar to original Bowie Dick Test Pack ",
        "✦ Easy to interpret,  Easy to document ",
        "✦ Independently tested to show performance similar to original pack ",
        "✦ Clear blue - violet color change  Non-Toxic / Lead Free",
        "✦ Dimensions: 105 x 65 x 6 mm ",
    },
     {
        id: 3,
        refa: " REF: 101.201.0100 Hollow A Helix with 1.5 mtr tube Unit: 100 indicators",
        "refb":" REF: 101.201.0250 Hollow A Helix with 1.5 mtr tube Unit: 250 indicators",
        name:"Bowie Dick Helix Test",
        file:"bowi-dick-helix-test.pdf",
        desciption:"Helix devices and their indicators have proven that they detect failures during each cycle much earlier than other chemical indicators / integrators.The EN 285 : 2009 are specifying the Helix test (Hollow A) to be used as Bowie Dick Test as wellas Batch Monitoring when hospitals are sterilizing Hollow Loads. Next to that this Bowie Dick Helix Test is an obligatory test for class B Bench Top Steam sterilizers.",
        image:"three.png",
        characteristics:["✦ Conform to ISO 11140 - 1 Type 2 - EN 867 part 5 class B     ",
        "✦ Clear transition of color into pink",
        "✦ Easy to interpret,  Easy to document",
        "✦ Non-Toxic / Lead Free, Can be fully recycled",
        "✦ PCD guaranteed for 500 Cycles (134°C - 3,5 min)",
    
    },
      {
        id: 4,
        refa: "REF: 101.203.0100 SS Helix with 4 mtr tube Unit: 100 indicators blue - pink ",
        "refb":"REF: 101.203.0250 SS Helix with 4 mtr tube Unit: 250 indicators blue - pink ",
        "refc":"REF: 101.203.0500 Re-fill set for 101.203.xxxx Unit: 500 indicators blue - pink",
        name:"Bowie Dick Helix Test SS",
        file:"bowi-helix-ss.pdf",
        desciption:"The Sterintech Bowie Dick Helix Test with Stainless Steel Helix and 4 mtr long tube can be used as Bowie Dick test for both load types: Hollow and Porous Loads Helix devices and their indicators have proven that they detect failures during each cycle. From leakages, bad steam conditions, non-condensable gases, time and temperature issues and forms a simple aid to release your load securely.",
        image:"four.png",
        characteristics:["✦ Conform to ISO 11140 - 1: 2014 Type 2     ",
        "✦ Clear transition of color into pink",
        "✦ Easy to interpret,  Easy to document",
        "✦ Non-Toxic / Lead Free, Can be fully recycled",
        "✦ Metal PCD guaranteed > 5000 times (when O-ring is replaced every 500 cycles)",
    },
       {
        id: 5,
        refa: "REF: 102.010.0050 Bowie Dick Test Sheet A4 Unit: 50 pieces ",
        "refb":"REF: 102.011.0050 Bowie Dick Test Sheet A5 Unit: 50 pieces",
        name:"Batch Control Helix Test Sheet",
        file:"batc-helix-sheet.pdf",
        desciption:" Used for daily monitoring of pre-vacuum steam sterilizer. Based upon the Bowie Dick test result the steam sterilizer is released for usage during the day. The Bowie Dick test detect failures like air leaks, insufficient vacuum, inadequate steam penetration. ",
        image:"five.png",
        characteristics:["✦ For 134 ºC - 3,5 min / 121 ºC - 15 min Dimension: DIN A4 or DIN A5 size  ",
        "✦ To be packed into pack as per standard / instructions Clear Blue to Pink color change",
        "✦ Easy to interpret,  Easy to document",
        "✦ Non-Toxic / Lead Free, Can be fully recycled",
        "✦ Fulfill requirements of EN 285 / Conform to ISO 11140 - 1:2014 Type 2",
     
    },
        {
        id: 6,
        refa: "REF: 103.203.0100 For 134°C - 3,5 / 121°C - 15 min cycles Unit: 100 indicators  ",
        "refb":"REF: 103.203.0250 For 134°C - 3,5 / 121°C - 15 min cycles Unit: 250 indicators ",
        "refc":"REF: 103.203.0500 For 134°C - 3,5 / 121°C - 15 min cycles Unit: 500 indicators",
        "refd":"REF: 103.203.0400 For 134°C - 3,5 / 121°C - 15 min cycles Unit: 400 indicators ",
        name:"Batch Control Helix Test",
        file:"batc-helix-test.pdf",
        desciption:"Helix devices and their indicators have proven that they detect failures during each cycle. From leakages, bad steam conditions, non-condensable gases, time and temperature issues and forms a simple aid to release your load securely. ",
        image:"six.png",
        characteristics:["✦ Conform to ISO 11140 - 1:2014 Type 2 ",
        "✦ Clear transition of color into pink",
        "✦ Easy to interpret,  Easy to document",
        "✦ Non-Toxic / Lead Free, Can be fully recycled",
        "✦ PCD guaranteed for 500 Cycles (134°C - 3,5 min)",
    },
         {
        id: 7,
        refa: "REF: 103.020.0100",
        name:"Batch Control Helix Test (VH₂O₂) ",
        file:"batc-helix-vho.pdf",
        desciption:"Helix devices and their indicators have proven that they detect failures during each cycle. From leakages, too less plasma, overloading, time and vacuum issues and forms a simple aid to release your load securely. The PCD is consisting of a 30 cm long tube with an internal diameter of 2mm which is the maximum internal lumen which can be sterilized effectively by plasma sterilizers (single open end)",
        image:"seven.png",
        characteristics:["✦ Conform to ISO 11140 - 1: 2014 Type 2 ",
        "✦ Clear transition of color into yellow",
        "✦ Easy to interpret,  Easy to document",
        "✦ Non-Toxic / Lead Free, Can be fully recycled",
        "✦ PCD guaranteed to min. 100 cycles",
    },
          {
        id: 8,
        refa: "REF: 103.230.0100 For Ethylene-Oxide Unit: 100 indicators ",
        "refb":"REF: 103.230.0250 For Ethylene-Oxide Unit: 250 indicators",
        "refc":" REF: 103.230.0500 For Ethylene-Oxide Unit: 500 indicators",
        name:"Batch Control Helix Test - Ethylene Oxide",
        file:"batc-helix-eo.pdf",
        desciption:"Helix devices and their indicators have proven that they detect failures during each cycle. From leakages, sterilization conditions like time and temperature issues as well as gas concentration and forms a simple aid to release your load securely",
        image:"eight.png",
        characteristics:["✦ Conform to ISO 11140 - 1:2014 Type 2",
        "✦ EO Cycle parameters: 600 mg/L - 54ºC - 60% RH Clear transition of color into yellow ",
        "✦ Easy to interpret,  Easy to document",
        "✦ Non-Toxic / Lead Free, Can be fully recycled",
        "✦ PCD guaranteed for 500 Cycles ",
        
    },
           {
        id: 9,
        refa: "REF: 103.240.0100 For Formaldehyde Unit: 100 indicators ",
        refa:"REF: 103.240.0250 For Formaldehyde Unit: 250 indicators",
        "refc":"REF: 103.240.0500 For Formaldehyde Unit: 500 indicators",
        name:"Batch Control Helix Test - Formaldehyde",
        file:"batc-helix-fo.pdf",
        desciption:"Helix devices and their indicators have proven that they detect failures during each cycle. From leakages, sterilization conditions like time and temperature issues as well as gas concentration and forms a simple aid to release your load securely. ",
        image:"nine.png",
        characteristics:["✦ Conform to ISO 11140 - 1:2014 Type 2 ",
        "✦ Clear transition of color into green ",
        "✦ Easy to interpret,  Easy to document",
        "✦ Non-Toxic / Lead Free, Can be fully recycled",
        "✦ PCD guaranteed for 500 Cycles ",
    },
            {
        id: 10,
        refa: "REF: 104.003.0500 Multi-parameter indicator 134°C-3,5 min / 121°C-15 min Unit: 500 pieces",
        name:"Steam Indicator - Type 4 ",
        file:"stea-indicator.pdf",
        desciption:"The multi-parameter indicator is checking time and temperature of the sterilization cycle at the exact place where the indicator is placed. A clear Violet to Green color change is indicating the correct steam sterilization cycle parameters have been met. The Sterintech™ Indicators are intended to be used during steam sterilization to check critical parameters at the place where they are placed.",
        image:"ten.png",
        characteristics:["✦ Shelf life : 5 years after production     ",
        "✦ Packed in an easy dispensing carton ",
        "✦ Non-Toxic / Lead Free, Clear color transition into green",
        "✦ Steam indicator conform to ISO 11140 :2014 Type 4",
        
   
    },
             {
        id: 11,
        refa: "REF: 104.022.0200 Plasma Indicator Unit: 200 pieces ",
        name:"Plasma Indicator - Type 4",
        file:"plasa-indicator.pdf",
        desciption:"These indicator strips can be used as in-pack indicator in order to detect sterilization conditions have been met inside the pack. The Sterintech™ Plasma Indicator has been tested by means of numerous cycles of Plasma sterilization in order to secure a proper working when used in various Plasma sterilizers. ",
        image:"eleven.png",
        characteristics:["✦ Shelf life : 5 years after production",
        "✦ Clear transition change from red to yellow",
        "✦ Conforms to ISO 11140 - 1:2014 Type 4",
        "✦ Non-Toxic / Based upon a PP Material",
        "✦ Very easy interpretation of result",
        "Dimensions: 75 x 20 mm (per strip)",
    },
              {
        id: 12,
        refa: "REF: 104.030.0250 Type 4 Long strip with EO indicator Unit: 250 pieces *EO: 600 mg/L - 54ºC - 60% RH ",
        name:"Type 4 Long strip with EO indicator ",
        file:"longeo-indicator.pdf",
        desciption:"These indicator strips can be used as in-pack indicator in order to detect sterilization conditions have been met inside the pack.The Sterintech™ Type 4 Long strip with EO indicator (length 19 cm) can be divided in the middle by means of a perforation into two Indicator strips (length 9,5 cm). ",
        image:"twelwe.png",
        characteristics:["✦ Conforms to ISO 11140 - 1 ",
        "✦ Shelf life : 5 years after production",
        "✦ Clear color change from Red to Yellow Very easy interpretation of result",
        "✦ Non-Toxic / no heavy metals, water based inks ",
        "✦ Based upon special paper suitable for EO sterilization.",
        "✦ Dimensions: 190 x 15 mm (per strip)",
     
    },
               {
        id: 13,
        refa: "REF: 104.004.0250 Type 4 Long strip with steam indicator Unit: 250 pieces * 134°C-3,5 min / 121°C-15 min ",
        name:"Type 4 Long strip with steam indicator ",
        file:"longsteam-indicator.pdf",
        desciption:"These indicator strips can be used as in-pack indicator in order to detect sterilization conditions have been met inside the pack.The Sterintech™ Type 4 Long strip with steam indicator (length 19 cm) can be divided in the middle by means of a perforation into two Indicator strips (length 9,5 cm). ",
        image:"thirteen.png",
         characteristics:["✦ Conforms to ISO 11140 - 1 ",
        "✦ Shelf life : 5 years after production",
        "✦ Clear color change from Red to Yellow Very easy interpretation of result",
        "✦ Non-Toxic / no heavy metals, water based inks ",
        "✦ Based upon special paper suitable for EO sterilization.",
        "✦ Dimensions: 190 x 15 mm (per strip)  Unit is 250 long strip indicators or 500 normal indicator strips when divided",
    },
                  {
        id: 14,
        refa: "REF: 104.304.0250 Type 4 Long strip with steam indicator Unit: 250 pieces *134°C-3,5 min / 121°C-15 min ",
        name:" Type 4 Long strip with steam indicator ",
        file:"longsteam-,ndicator-new.pdf",
        desciption:"These indicator strips can be used as in-pack indicator in order to detect sterilization conditions have been met inside the pack. ",
        image:"fourteen.png",
        characteristics:["✦ Conforms to ISO 11140 - 1:2014 - Type 4 ",
        "✦ Shelf life : 5 years after production",
        "✦ Clear color change from violet to green Very easy interpretation of result",
        "✦ Non-Toxic / Based upon special paper suitable for steam sterilization and self-adhesive",
        "✦ no heavy metals , water based inks",
        "✦ Dimensions: 140 x 23 mm (per long strip)* Unit is 250 long strip indicators or 500 normal indicator strips when divided",
    },
     {
        id: 15,
        refa: "REF: 105.030.0500 EO Integrator Unit: 500 pieces ",
        "refb":"REF: 105.230.0500 EO Integrator Self-Adhesive Unit: 500 pieces EO: 600 mg/L - 54ºC - 60% RH",
        name:" EO Integrator - Type 5",
        file:"eo-itegrator.pdf",
        desciption:"Integrators can be used in addition to the batch control Helix which will allow you to release load. Especially when OR staff wants to be re-affirmed about the sterilization conditions inside trays or containers EO Integrators are giving a clear result which easily can be interpreted by the end-user bycomparing it to the reference color printed on the integrator. No misunderstanding possible. ",
        image:"fifteen.png",
        characteristics:["✦ EO Integrator conform to ISO 11140 - Type 5 ",
        "✦ Shelf life : 5 years after production",
        "✦ Clear color transition into Light Orange / Yellow",
        "✦ Non-Toxic / Packed in an easy dispensing carton",
        "✦ no heavy metals , water based inks",
        "✦ Dimensions: 55 x 25 mm per strip",
    },
                 {
        id: 16,
        refa: "REF: 105.103.0250 Moving front Integrator - Small Unit: 250 pieces",
        "refb":"REF: 105.303.0500 Moving front Integrator - Small Unit: 500 pieces",
        "refc":" REF: 105.103.1000 Moving front Integrator - Small Unit: 1000 pieces",
        name:"Moving Front Integrator - Small - Type 5 ",
        file:"movig-integrator-small.pdf",
        desciption:"Integrators can be used in addition to the batch control Helix which will allow you to release load. The moving front integrators Type 5 gives you a detailed information about the sterilization cycle. The Sterintech™ Moving Front Integrators are giving you the best interpretation possible in case of any failure in your steam sterilization cycle. If temperature is not reached or holding time was too short the dark color will not reach the accept area. The MFI is also suitable for 121°C- 20 min cycles. ",
        image:"sixteen.png",
        characteristics:["✦ Shelf life : 5 years after production     ",
        "✦ Packed in white aluminum re-closable bags",
        "✦ Moving front Integrator conform to ISO 11140 - Type 5 - SV; 134°C-3,5 min",
        "✦ Non-Toxic / Lead Free, Complete indicator area sealed of by foil",
        "✦ Very easy interpretation of result",
       
    },
                  {
        id: 17,
        refa: "REF: 105.103.0500 Steam Integrator 134°C-3,5 min Unit: 500 pieces 121°C-15 min",
        name:"Steam Integrator - Type 5",
        file:"stea-integrator.pdf",
        desciption:"Integrators can be used in addition to the batch control Helix which will allow you to release load. Especially when OR staff wants to be re-affirmed about the sterilization conditions inside trays or containers.Steam Integrators are giving a clear result which easily can be interpreted by the end-user by comparing it to the reference color printed on the integrator. No misunderstanding possible. ",
        image:"seventeen.png",
        characteristics:["✦ Steam Integrator conform to ISO 11140 - Type 5 ",
        "✦ Shelf life : 5 years after production",
        "✦ Packed in an easy dispensing carton",
        "✦ Non-Toxic / Lead Free",
        "✦ Clear color transition from blue into pink of lacquer covered indicator",
      
    },
  {
        id: 18,
        refa: "REF: 105.203.0500 Steam Integrator 134°C-3,5 min Unit: 500 pieces 121°C-15 min ",
        name:"Steam Integrator - Type 5 - Self-adhesive",
        file:"stea-integrator-large.pdf",
        desciption:"Integrators can be used in addition to the batch control Helix which will allow you to release load.Especially when OR staff wants to be re-affirmed about the sterilization conditions inside trays or containers. Steam Integrators are giving a clear result which easily can be interpreted by the end-user by comparing it to the reference color printed on the integrator. No misunderstanding possible. ",
        image:"eighteen.png",
        characteristics:["✦ Steam Integrator conform to ISO 11140 - Type 5",
        "✦ Clear area to write details like dates, department, operator",
        "✦ Shelf life : 5 years after production",
        "✦ Non-Toxic / Lead Free, Packed in an easy dispensing carton",
        "✦ Lacquer covered indicator Clear color transition from blue into pink ",
        
    },
   {
        id: 19,
        refa: "REF: 106.103.0500 Emulator 134°C-3,5 min/121°C-15 min Unit: 500 pieces ",
        "refb":"REF: 106.103.0500SA Emulator 134°C-3,5 min/121°C-15 min self-adhesive Unit: 500 pieces",
        name:"Steam Emulator - Type 6 ",
        file:"stea.emulator.pdf",
        desciption:"Emulators can be used in addition to the batch control Helix which will allow you to release load. Especially when OR staff wants to be re-affirmed about the sterilization conditions. The Sterintech™ Emulators are offering you more information about the steam sterilization process by means of the very accurate indicator fields of the Emulator. These Emulators can detect many disturbances of the sterilization parameters inside packs or containers.",
        image:"nineteen.png",
        characteristics:["✦ Steam emulator conform to ISO 11140 - Type 6 ",
        "✦ Shelf life : 5 years after production ",
        "✦ Clear color transition from Blue into Pink",
        "✦ Non-Toxic / Lead Free",
        "✦ Chemical emulator covered with lacquer",
    },
    {
        id: 20,
        refa: "REF: 106.203.0500 Steam Emulator 134°C-3,5 min/ Unit: 500 pieces 121°C-15 min",
        name:"Emulator - Type 6 - Self-Adhesive",
        file:"emultor-self.pdf",
        desciption:"Emulators can be used in addition to the batch control Helix which will allow you to release load. Especially when OR staff wants to be re-affirmed about the sterilization conditions. The Sterintech™ Emulators are offering you more information about the steam sterilization process by means of the very accurate indicator fields of the Emulator. These Emulators can detect many disturbances of the sterilization parameters inside packs or containers.",
        image:"twenty.png",
        characteristics:["✦ Steam emulator conform to ISO 11140 - Type 6",
        "✦ Clear area to write details like dates, department, operator",
        "✦ Shelf life : 5 years after production",
        "✦ Non-Toxic / Lead Free, Packed in an easy dispensing carton",
        "✦ Chemical emulator covered with lacquer Clear color transition from Blue into Pink",
       
    },
     {
        id: 21,
        refa: "REF: 106.018.0250 Sequential Emulator 134°C-18 min Unit: 250 pieces ",
        name:"Emulator - Type 6 - 18 min",
        file:"emultor.pdf",
        desciption:"Emulators can be used in addition to the batch control Helix which will allow you to release load. Especially when OR staff wants to be re-affirmed about the sterilization conditions. The Sterintech™ Emulators are offering you exact information about the steam sterilization process inside your container or pouch. A clear yellow to black color change is helping you interpreting the results in the proper way.  ",
        image:"twentyone.png",
        characteristics:["✦ Shelf life : 5 years after production ",
        "✦ Packed in an easy dispensing carton",
        "✦ Steam emulator conform to ISO 11140 - Type 6",
        "✦ Non-Toxic / Lead Free, Clear color transition into black of the emulator",
        "✦ Chemical emulator covered with lacquer",
       
    },
      {
        id: 22,
        refa: "REF: 120.001.0001 Dual Incubator for SCBI Unit: 1 piece",
        name:"Digital Incubator for SCBI ",
        file:"digial-incubator.pdf",
        desciption:"The Sterintech Digital Incubator for SCBI is a accurate dry bed incubator with a maximum of 18 positions to incubate the SCBI’s. A micro-processor control and digital display for feed-back the unit is easily controlled having three standard programs. Once placed the SCBI it takes one push at the button to start the incubation period. Upon completion of the cycle the DI SCBI will give an audible alarm.",
        image:"twentytwo.png",
        characteristics:["✦ Power supply range 90- 270 VAC / 50 – 60 Hz)",
        "✦ Capacity: max. 18 SCBI",
        "✦ Three standard incubation programs: • 37°C / 48 hrs (EO) • 56-59°C / 24 hrs (STEAM ) • 56-59°C / 24 hrs (Plasma)",
        "✦ Dimensions: 22 x 27 x 21 cm , weight : 3,8 kg",
        
    },
       {
        id: 24,
        refa: "REF: 107.010.0100 SCBI for STEAM, pop. 1x10E6 Unit: 100 pieces ",
        "refb":"REF: 120.001.0001 Dual Incubator for SCBI Unit: 001 piece",
        name:"SCBI for STEAM with 8 hour PH reaction",
        file:"scbieight-hrs.pdf",
        desciption:"The monitoring of sterilization condition at preferred places with the help of Self Contained Biological Indicators (or SCBI) is no longer practice of every day in European Hospitals and mainly used during validation of the sterilizers, whereas outside Europe the SCBI is widely used for daily routine checks of sterilizers in Hospitals.",
        image:"twentythree.png",
        characteristics:["✦ Biological Indicators conform to ISO 11138 ",
        "✦ SCBI STEAM: Geobacillus Stearothermophilus ATCC 7953 1x10E6 spores per vial",
        "✦ EColor change: Purple to Yellow (STEAM)",
        "✦ Digital Incubator (220V) for 60°C / 8 hrs (STEAM)",
      
    },
        {
        id: 25,
        refa: "REF: 107.001.0100 SCBI for STEAM, pop. 1x10E6 Unit: 100 pieces  ",
        "refb":"REF: 107.002.0100 SCBI for Plasma, pop. 1x10E6 Unit: 100 pieces",
        "refc":"REF: 107.003.0100 SCBI for EO, pop. 1x10E6 Unit: 100 pieces ",
        "refd":"REF: 107.003.0100 SCBI for EO, pop. 1x10E6 Unit: 100 pieces ",
        "refe":"REF: 120.001.0001 Dual Incubator for SCBI Unit: 001 piece",
        name:"SCBI for STEAM, Plasma & Ethylene-Oxide",
        file:"scbieo-twentyfour.pdf",
        desciption:"The monitoring of sterilization condition at preferred places with the help of Self Contained Biological Indicators (or SCBI) is no longer practice of every day in European Hospitals and mainly used during validation of the sterilizers, whereas outside Europe the SCBI is widely used for daily routine checks of sterilizers in Hospitals.",
        image:"twentyfour.png",
        characteristics:["✦ Biological Indicators conform to ISO 11138",
        "✦ SCBI EO: Bacillus Atrophaeus ATCC 9372 1x10E6 spores per vial",
        "✦ SCBI STEAM/Plasma: Geobacillus Stearothermophilus ATCC 7953 1x10E6 spores per vial",
        "✦ Color change: Green to yellow (EO) and purple to yellow (STEAM)",
        "✦ Digital Incubator (220V) for 37°C / 48 hrs (EO) and 60°C / 24 hrs (STEAM & Plasma)",
        
    },
         {
        id: 23,
        refa: "REF: 107.030.0100 SCBI for EO, pop. 1x10E6 Unit: 100 pieces  ",
        "refb":"REF: 120.001.0001 Dual Incubator for SCBI Unit: 001 piece",
        name:"SCBI for EO - 12 hour PH reaction",
        file:"scbieo-twelwe.pdf",
        desciption:"The development towards quicker read-outs of SCBI is still ongoing , most of the solutions require a Quick Read-out Incubator which is expensive to acquire. The new Sterintech SCBI EO is giving a PH reaction with a normal dry bed incubator in 12 hours time only. An improvement compared to our previous model which was needing 48 hours of incubation.",
        image:"twentyfive.png",
        characteristics:["✦ Biological Indicator conform to ISO 11138 and ISO 11138-2 ",
        "✦ SCBI EO: Bacillus Atrophaeus ATCC 7953",
        "✦ Population: 1x10E6 spores per vial",
        "✦ Color change: Orange to bright Yellow",
        
       
    },
          {
        id: 26,
        refa: "REF: 107.100.0050 SCBI for STEAM, pop. 1x10E6 Unit: 50 pieces ",
        "refb":"REF: 107.200.0050 SCBI for Plasma, pop. 1x10E6 Unit: 50 pieces",
        "refc":"REF: 120.003.0001 Quick Readout Incubator 2.0 Unit: 1 piece ",
        "refd":"REF: 120.010.0001 SCBI Crusher Unit: 1 piece",
        name:"Quick Read-out Biological Indicator (SCBI)",
        file:"scbiquick-one-hrs.pdf",
        desciption:"The Sterintech™ Quick Read-out Biological Indicators (SCBI) are intended to monitor the sterilization condition at specific places inside the load of a sterilizer. SP Medikal is recommending the use of a BI Helix device in combination with the SCBI in order to ensure that air removal and steam penetration is taking into the equation.",
        image:"twentysix.png",
        characteristics:["✦ Biological Indicators conform to ISO 11138",
        "✦ Spores: Geobacillus Stearothermophilus ATCC 7953 1x10E6 spores per vial",
        "✦ Color change: Purple to yellow (growth media)",
        "✦ Digital Incubator (220V) for 60°C / max. 1 hour for fluorescent enzymatic results.",
       
    },
           {
        id: 27,
        refa: "REF: 107.010.0050 SCBI for Steam, pop. 1x10E6 - 20 min Unit: 50 pieces ",
        "refb":"REF: 107.020.0050 SCBI for Plasma, pop. 1x10E6 - 20 min Unit: 50 pieces",
        "refc":" REF: 107.100.0050 SCBI for Steam, pop. 1x10E6 - 1 hour Unit: 50 pieces ",
        "refd":"REF: 107.200.0050 SCBI for Plasma, pop. 1x10E6 - 1 hour Unit: 50 pieces",
        "refe":" REF: 120.003.0001 Quick Readout Incubator 2.0 Unit: 1 piece",
        name:"Quick Read-out Biological Indicators (SCBI)",
        file:"scbitwenty-min.pdf",
        desciption:"The Sterintech™ Quick Read-out Biological Indicators (SCBI) are intended to monitor the sterilization condition at specific places inside the load of a sterilizer. SP Medikal is recommending the use of a BI Helix device in combination with the SCBI in order to ensure that air removal and steam penetration is taking into the equation.",
        image:"twentyseven.png",
        characteristics:["✦ Biological Indicators conform to ISO 11138 ",
        "✦ Spores: Geobacillus Stearothermophilus ATCC 7953 1x10E6 spores per vial",
        "✦ Color change: Purple to yellow (growth media)",
        "✦ Digital Incubator (220V) for 60°C for fluorescent enzymatic results.",
        
    },
            {
        id: 28,
        refa: "REF: 602.002.0001 Two line label gun Unit: 1 piece ",
        "refb":"REF: 609.102.0001 Ink roller for two line label gun Unit: 1 piece ",
        "refc":" REF: 602.011.9000 Label with Steam indicator Unit: 9.000 labels",
        "refd":" REF: 602.021.9000 Label with Plasma indicator Unit: 7.200 labels",
        "refe":"REF: 602.031.9000 Label with EO indicator Unit: 9.000 labels ",
        name:"2-Line Label guns & Labels ",
        file:"two-ine-label-gun.pdf",
        desciption:"The Sterintech two line label gun is reliable, easy to use and durable. It will serve for years of intensive usage. Sterintech double labels for two line label guns are available with all type of sterilization indicators as well as a variety of colors. Colored labels are used to assist FIFO systems as well as easy recognition of sterile goods for a certain department. Often the combination of a double label gun label and normal tape is a more cost-effective solution than steam tapes only. Next to that they offer better readable data and prevent writing errors.",
        image:"twentyeight.png",
        characteristics:["✦ Process Indicators (Steam, FO, EtO, Plasma) conform to ISO 11140 - 1 Type 1 ",
        "✦Clear transition of indicator into its end-color Easy to use label gun",
        "✦ Double labels serve for an easy traceability and documentation",
        "✦ Non-Toxic / Lead Free, Can be fully recycled indicators",
        "✦ Latex free label materials",
     
    },
             {
        id: 29,
        refa: "REF: 603.003.0001 Three line label gun Unit: 1 piece  ",
        "refb":"REF: 609.103.0001 Ink roller for three line label gun Unit: 1 piece ",
        "refc":"REF: 603.011.9000 Label with Steam indicator Unit: 9.000 labels",       
        "refd":"REF: 603.021.9000 Label with Plasma indicator Unit: 6.000 labels ",
        "refe":"REF: 603.030.9000 Label with EO indicator Unit: 9.000 labels",
        name:"3-Line Label guns & Labels",
        file:"thre-line-label-gun.pdf",
        desciption:"The Sterintech™ three line label gun is reliable, easy to use and durable. It will serve for years of intensive usage. Sterintech™ double labels for three line label guns are available with all type of sterilization indicators as well as a variety of colors. Colored labels are used to assist FIFO systems as well as easy recognition of sterile goods for a certain department. Often the combination of a double label gun label and normal tape is a more cost-effective solution than steam tapes only. Next to that they offer better readable data and prevent writing errors",
        image:"twentynine.png",
        characteristics:["✦ Process Indicators (Steam, FO, EtO, Plasma) conform to ISO 11140 - 1 Type 1",
        "✦ Clear transition of indicator into its end-color ",
        "✦ Easy to use label gunDouble labels serve for an easy traceability and documentation",
        "✦ Non-Toxic / Lead Free, Can be fully recycled indicators",
        "✦ Latex free label materials",
        
    },
              {
        id: 30,
        refa: "REF: 603.203.0001 Three line label gun Unit: 1 piece  ",
        "refb":"REF: 609.104.0001 Ink roller for Three line label gun Unit: 1 piece ",
        "refc":"REF: 606.010.7500 Label with Steam indicator Unit: 7.500 labels",
        "refd":"REF: 606.020.7500 Label with Plasma indicator Unit: 7.500 labels ",
        "refe":"REF: 606.030.7500 Label with EO indicator R-Y Unit: 7.500 labels",
        name:"3-Line Label guns & Labels",
        file:"thre-line-label-gun-second.pdf",
        desciption:"The Sterintech™ three line label gun is reliable, easy to use and durable. It will serve for years of intensive usage. Sterintech™ double labels for three line label guns are available with all type of sterilization indicators as well as a variety of colors. Colored labels are used to assist FIFO systems as well as easy recognition of sterile goods for a certain department. Often the combination of a double label gun label and normal tape is a more cost-effective solution than steam tapes only. Next to that they offer better readable data and prevent writing errors.",
        image:"thirty.png",
        characteristics:["✦ Process Indicators (Steam, FO, EtO, Plasma) conform to ISO 11140 - 1 Type 1",
        "✦ Clear transition of indicator into its end-color",
        "✦ Easy loading of labels into gun Double labels serve for an easy traceability and documentation",
        "✦ Non-Toxic / Lead Free, Can be fully recycled indicators",
        "✦ Latex free label materials",
       
    },
    {
        id: 31,
        refa: "REF: 202.025.3000 Soft Crepe 60 gr/sqm Blue 25x25cm Unit: 3.000 pcs  ",
        "refb":"REF: 202.040.1000 Soft Crepe 60 gr/sqm Blue 40x40cm Unit: 500 pcs ",
        "refc":"REF: 202.075.0250 Soft Crepe 60 gr/sqm Blue 75x75cm Unit: 250 pcs",
        name:"Soft Crepe Paper",
        file:"softcrepe-paper.pdf",
        desciption:"Today Infection control is getting increasingly important since more and more bacterias starts to get resistant to the latest anti-biotics. Infection Prevention is the key word. Crepe papers are essential for both Sterility Assurance and Infection Prevention in its function as Sterile Barrier for Medical Devices. Sterintech Soft Crepe papers can be used as an inner or outer wrap and serve as a sterile field in combination with non-woven and textile materials. ",
        image:"thirtyone.png",
        characteristics:["✦ Water repellent Microbial Barrier",
        "✦ High resistance to puncture and tearing Soft, strong and memory free",
        "✦ Can serve as Infection prevention measurere",
        "✦ Compliant to standard ISO 11607-1 and EN 868 - 2 Compatible to STEAM, FORM or EO sterilization methods",
       
    },
                 {
        id: 32,
        refa: "REF: 208.025.3000 Soft Crepe 60 gr/sqm Blue/Green 25x25cm Unit: 3.000 pcs   ",
        "refb":"REF: 208.045.1000 Soft Crepe 60 gr/sqm Blue/Green 45x45cm Unit: 1.000 pcs ",
        "refc":"REF: 208.075.0250 Soft Crepe 60 gr/sqm Blue/Green 75x75cm Unit: 250 pcs.",
        "refd":"REF: 208.120.0125 Soft Crepe 60 gr/sqm Blue/Green 120x120cm Unit: 125 pcs",
        name:"Soft Crepe Paper Blue/Green",
        file:"softcrepe-paper-bg.pdf",
        desciption:"Today Infection control is getting increasingly important since more and more bacterias starts to get resistant to the latest anti-biotics. Infection Prevention is the key word. Crepe papers are essential for both Sterility Assurance and Infection Prevention in its function as Sterile Barrier for Medical Devices. Sterintech Soft Crepe papers can be used as an inner or outer wrap and serve as a sterile field in combination with non-woven and textile materials. The Blue /Green combination is making recognition of damaged packs a lot easier due to the color difference of the outer and inner wrap.",
        image:"thirtytwo.png",
        characteristics:["✦ Water repellent Microbial Barrier",
        "✦ High resistance to puncture and tearing Soft, strong and memory free",
        "✦ Can serve as Infection prevention measurere",
        "✦ Compliant to standard ISO 11607-1 and EN 868 - 2 Compatible to STEAM, FORM or EO sterilization methods",
       
    },
                  {
        id: 33,
        refa: "REF: 212.025.3000 Soft Crepe 60 gr/sqm Green 25x25cm Unit: 3.000 pcs ",
        "refb":"REF: 212.040.1000 Soft Crepe 60 gr/sqm Green 40x40cm Unit: 500 pcs ",
        "refc":"REF: 212.075.0250 Soft Crepe 60 gr/sqm Green 75x75cm Unit: 250 pcs ",
        "refd":"REF: 212.120.0125 Soft Crepe 60 gr/sqm Green 120x120cm Unit: 125 pcs ",
        name:"Soft Crepe Paper - Green",
        file:"softcrepe-paper-green.pdf",
        desciption:"Today Infection control is getting increasingly important since more and more bacterias starts to get resistant to the latest anti-biotics. Infection Prevention is the key word. Crepe papers are essential for both Sterility Assurance and Infection Prevention in its function as Sterile Barrier for Medical Devices. Sterintech Soft Crepe papers can be used as an inner or outer wrap and serve as a sterile field in combination with non-woven and textile materials. ",
        image:"thirtythree.png",
        characteristics:["✦ Water repellent Microbial Barrier",
        "✦ High resistance to puncture and tearing Soft, strong and memory free",
        "✦ Can serve as Infection prevention measurere",
        "✦ Compliant to standard ISO 11607-1 and EN 868 - 2 Compatible to STEAM, FORM or EO sterilization methods",
      
    },
                   {
        id: 34,
        refa: "REF: 224.050.0400 SMS Non-woven 43 gr/sqm Blue 50x50cm Unit: 300 pcs ",
        "refb":"REF: 205.075.0200 SMS Non-woven 43 gr/sqm Green 75x75cm Unit: 200 pcs",
        "refc":" REF: 209.075.0200 SMS Non-woven 43 gr/sqm Green/Blue 75x75cm Unit: 200 pcs",
        name:"Non-woven SMS - Green / Blue",
        file:"non-owen.pdf",
        desciption:"Today Infection control is getting increasingly important since more and more bacterias starts toget resistant to the latest anti-biotics. Infection Prevention is the key word. SMS materials are essential for both Sterility Assurance and Infection Prevention in its function as Sterile Barrier for Medical Devices. Sterintech SMS can be used as an outer wrap and serve as a sterile field.",
        image:"thirtyfour.png",
        characteristics:["✦ Water repellent Microbial Barrier",
        "✦ High resistance to puncture and tearing Soft, strong and memory free",
        "✦ Can serve as Infection prevention measurere",
        "✦ Compliant to standard ISO 11607-1 and EN 868 - 2 Compatible to STEAM, FORM or EO sterilization methods",
        
    },
     {
        id: 35,
        refa: "REF: 301.050.0001 Flat reel, 60 gr/sqm, 50 mm x 200 mtr Unit: 1 pcs  ",
        "refb":"REF: 302.075.0001 Gusseted reel, 60 gr/sqm, 75 mm x 100 mtr Unit: 1 pcs",
        name:"Sterilization Rolls - 60 gsm - green film",
        file:"sterl-sixty.pdf",
        desciption:"Today Infection control is getting increasingly important since more and more bacterias starts to get resistant to the latest anti-biotics. Infection Prevention is the key word. Sterilization packaging materials have been developed over many years to increase the stability of the sterile barrier over time. Sterintech™ Sterilization rolls are used to wrap medical devices. The flexibility of length cutting is making a dedicated packaging of individual instruments possible and offer a number of advantages to the end-user",
        image:"thirtyfive.png",
        characteristics:["✦ Easy recognition of content by the multi-layer transparent film ",
        "✦ Indicators and text printed outside the packing area Strong , multi-line seals",
        "✦ Non-tearing film avoids tearing at opening the pack Clean and fibre-free opening of pack",
        "✦ Compliant to standard ISO 11607-1, EN 868 - 5 and ISO 11140-1",
        "✦ Compatible to STEAM, EO and FORM sterilization by three imprinted indicators",
        
    },
                     {
        id: 36,
        refa: "REF: 311.050.0001 Flat reel, 70 gr/sqm, 50 mm x 200 mtr Unit: 1 pcs ",
        "refb":"REF: 312.075.0001 Gusseted reel, 70 gr/sqm, 75 mm x 100 mtr Unit: 1 pcs ",
        name:"Sterilization Rolls - 70 gsm - green film",
        file:"sterl-seventy.pdf",
        desciption:"Today Infection control is getting increasingly important since more and more bacterias starts to get resistant to the latest anti-biotics. Infection Prevention is the key word. Sterilization packaging materials have been developed over many years to increase the stability of the sterile barrier over time. Sterintech™ Sterilization rolls are used to wrap medical devices. The flexibility of length cutting is making a dedicated packaging of individual instruments possible and offer a number of advantages to the end-user",
        image:"thirtysix.png",
        characteristics:["✦ Easy recognition of content by the multi-layer transparent film ",
        "✦ Indicators and text printed outside the packing area Strong , multi-line seals",
        "✦ Non-tearing film avoids tearing at opening the pack Clean and fibre-free opening of pack",
        "✦ Compliant to standard ISO 11607-1, EN 868 - 5 and ISO 11140-1",
        "✦ Compatible to STEAM, EO and FORM sterilization by three imprinted indicators",
        
    },
                      {
        id: 37,
        refa: "REF: 303.075.0001 Flat reel, 1059B, 75 mm x 70 mtr Unit: 1 pcs ",
        "refb":"REF: 303.100.0001 Flat reel, 1059B, 100 mm x 70 mtr Unit: 1 pcs",
        name:"Sterilization Rolls (Tyvek 1059B)",
        file:"sterl-tyvek.pdf",
        desciption:"Today Infection control is getting increasingly important since more and more bacterias starts to get resistant to the latest anti-biotics. Infection Prevention is the key word. Sterilization packaging materials have been developed over many years to increase the stability of the sterile barrier over time. Sterintech™ Sterilization rolls (Tyvek) are used to pack medical devices for Plasma Sterilization. The flexibility of length cutting is making a dedicated packaging of individual instruments possible and offer a number of advantages to the end-user",
        image:"thirtyseven.png",
        characteristics:["✦ Easy recognition of content by the multi-layer transparent film ",
        "✦ Indicators and text printed outside the packing area Strong , strong seal",
        "✦ Non-tearing film avoids tearing at opening the pack Clean and fibre-free opening of pack",
        "✦ Compliant to standard ISO 11607-1, EN 868 - 5 and ISO 11140-1",
        "✦ Compatible to STEAM, EO and FORM sterilization by three imprinted indicators",
        
    },
                       {
        id: 38,
        refa: "REF: 502.019.0048 Steam tape 19 mm x 50 mtr Unit: 48 pieces ",
        "refb":"REF: 502.025.0036 Steam tape 25 mm x 50 mtr Unit: 36 pieces ",
        name:"Steam Tapes",
        file:"stea-tape.pdf",
        desciption:"Especially selected for the various steam sterilization processes the Sterintech™ steam tapes provide a good stickiness to most surfaces.Providing a quick recognition of sterile goods by it’s indicator (yellow-dark) while securing the sterility of wrapped items our steam tape performs in Hospitals anywhere in the world.  ",
        image:"thirtyeight.png",
        characteristics:["✦ Single packed to guarantee shelf-life specifications up to 3 years after production",
        "✦ Easy unwinding from the roll Adhesive works well on Soft Crepe and Non-Woven materials",
        "✦ Steam indicator conform to ISO 11140 - Type 1",
        "✦ Clear yellow - dark color transition of the indicator",
        "✦ Latex free glue Non-Toxic / Heavy metal free Suitable for steam cycles 121 and 134 Degrees Celsius",
       
    },
                        {
        id: 39,
        refa: "REF: 503.119.0048 White tape EO 19 mm x 50 mtr Unit: 48 pieces",
        name:"EO Gas Indicator Tapes",
        file:"eo-gs-indicator.pdf",
        desciption:"Especially developed for the EO sterilization processes the Sterintech Indicator tapes provide a good stickiness to most surfaces Providing a quick recognition of sterile goods by it’s indicator while securing the sterility of wrapped items the White Indicator tapes performs well in Hospitals anywhere in the world. ",
        image:"thirtynine.png",
        characteristics:["✦ EO Gas indicator conform to ISO 11140 - Type 1 ",
        "✦ Clear color transition of the indicator from red to yellow",
        "✦ Latex free glue Non-Toxic / Heavy metal free",
        "✦ Single packed to guarantee shelf-life specifications up to 3 years after production",
        "✦ Easy unwinding from the roll ",
        
    },
                         {
        id: 40,
        refa: "REF: 502.019.0048 White tape steam 19 mm x 50 mtr Unit: 48 pieces ",
        "refb":"REF: 502.025.0036 White tape steam 25 mm x 50 mtr Unit: 36 pieces",
        name:"White Tapes Steam",
        file:"whit-tape.pdf",
        desciption:"Especially selected for the various steam sterilization processes the Sterintech™ White tapes provide a good stickiness to most surfaces. Providing a quick recognition of sterile goods by it’s indicator (yellow-dark) while securing the sterility of wrapped items our steam tape performs in Hospitals anywhere in the world. ",
        image:"forty.png",
        characteristics:["✦ Single packed to guarantee shelf-life specifications up to 3 years after production",
        "✦ Easy unwinding from the roll Adhesive works well on Soft Crepe and Non-Woven materials",
        "✦ Steam indicator conform to ISO 11140 - Type 1",
        "✦ Clear yellow - dark color transition of the indicator",
        "✦ Latex free glue Non-Toxic / Heavy metal free ",
        "✦ Suitable for steam cycles 121 and 134 Degrees Celsius ",
       
    },
                          {
        id: 41,
        refa: "REF: 504.019.0001 Plasma tape 19 mm x 60 meter Unit: 1 piece ",
        name:"Plasma Tape - 19 mm x 60 meter",
        file:"plasa-tape.pdf",
        desciption:"Especially selected for the Plasma sterilization processes the Sterintech™ Plasma tapes provide a good stickiness to most surfaces. Now with a reference color as a post-sterilization reference Providing a quick recognition of sterile goods by it’s indicator while securing the sterility of wrapped items our plasma tape performs in Hospitals anywhere in the world ",
        image:"fortyone.png",
        characteristics:["✦ Single packed to guarantee shelf-life specifications up to 2 years after production  ",
        "✦ Easy unwinding from the roll and easy tearing by the side",
        "✦ Plasma indicator conform to ISO 11140 - Type 1",
        "✦ Latex free glue Non-Toxic / Heavy metal free ",
        "✦ Clear red - yellow color transition of the indicator",
        
    },
     {
        id: 42,
        refa: "REF: 902.111.1000 Container seal, blue 2,7 cm Unit: 1000 pieces ",
        "refb":"REF: 902.112.1000 Container seal, blue 2,7 cm with steam ind. Unit: 1000 pieces ",
        "refc":" REF: 902.113.1000 Container seal, red 2,7 cm Unit: 1000 pieces",
        "refd":"REF: 902.114.1000 Container seal, red 2,7 cm with steam ind. Unit: 1000 pieces",
        name:"Container Seal - 2,7 cm long pin",
        file:"continer-seal.pdf",
        desciption:"In order to secure the container for opening by un-authorized staff the container seals are offering an important shackle in the quality management chain. Prevents opening by un-authorized staff. Only by breaking the seal the container can be opened. A check at the OR for broken seals is guaranteeing the sterility of materials from the moment of sterilization till the actual use",
        image:"fortytwo.png",
        characteristics:["✦ Produced in polypropylene , softening above 150°C",
        "✦ Suitable for steam sterilization processes",
        "✦ Fulfilling EN 868 part 8 section 4.2.3",
        "✦ Steam indicator conform to ISO 11140 - Type 1",
        "✦ Clear color transition of the steam indicator",
        
    },
     {
         id:43,
         refa:"REF: 902.105.1100 Container seal, self-adhesive with pin Unit: 1100 pieces",
         name:"Self-Adhesive Container Seal Label",
         description:"In order to secure the container for opening by un-authorized staff the Self-Adhesive container seals are offering an important shackle in the quality management chain. Prevents opening by unauthorized staff. Only by breaking the seal the container can be opened. A check at the OR for broken seals is guaranteeing the sterility of materials from the moment of sterilization till the actual use.",
         file:"self-adhesive-scontainer-seal.pdf",
         image:"fortythree.png",
         characteristics:["✦ Produced from 180 gr/sqm paper.",
         "✦ Suitable for steam sterilization processes",
         "✦ Fulfilling EN 868 part 8 section 4.2.3 ",
         "✦ Can be fully recycled",
         "✦ Steam indicator conform to ISO 11140 - Type 1",
         "✦ Clear color transition of the indicator",]
         },
      {
         id:44,
         refa:"REF: 905.220.0100 Instrument Protector Small 50 x 160 mm Unit: 100 pieces ",
         name:"Instrument Protector Small",
         description:"Where ever the risk exist of sharp objects / instruments are damaging the sterile barrier the use of Instrument protector is advised. Fixating the instrument and covering the sharp edges by a highly puncture resistant material is reducing the risk of non-sterility of your operating instruments. The Instrument Protector Small is coming in 1 size only. Other sizes can be requested for. ",
         file:"instrument-small.pdf",
         image:"fortyfor.png",
         characteristics:["✦ Produced from 300 gr/sqm PP",
         "✦ Multiple times usable ",
         "✦ Suitable for steam sterilization processes",
         "✦ Can be fully recycled.",
         "Other types and dimensions available upon request. ",
         "",]
         },
       {
         id:45,
         refa:"REF: 905.201.0100 Instrument-Fix - Small 80 x 140 mm Unit: 100 pieces ",
         "refb":"REF: 905.202.0100 Instrument-Fix - Medium 89 x 165 mm Unit: 100 pieces",
         "refc":" REF: 905.203.0100 Instrument-Fix - Large 100 x 198 mm Unit: 100 pieces ",
         "refd":"REF: 905.204.0100 Instrument-Fix - X-Large 125 x 256 mm Unit: 100 pieces",
         name:"Sterile Barrier protector: Instrument-Fix",
         description:"Where ever the risk exist of sharp objects / instruments are damaging the sterile barrier the use of Instrument-Fix is advised. Fixating the instrument and covering the sharp edges by a highly puncture resistant material is reducing the risk of non-sterility of your operating instruments. The Instrument-Fix is coming in 4 standard sizes",
         file:"instrument-fix.pdf",
         image:"fortyfive.png",
         characteristics:["✦ Produced from 200 gr/sqm paper and high puncture resistant resin",
         "✦ Suitable for steam / Ethylene Oxide and Formaldehyde sterilization processes",
         "✦ Can be fully recycled.",
         "",
         "",
         "",]
         },
        {
         id:46,
         refa:"REF: 905.211.0100 Instrument-Fix - Small 80 x 140 mm Unit: 100 pieces ",
         "refb":"REF: 905.212.0100 Instrument-Fix - Medium 89 x 165 mm Unit: 100 pieces",
         "refc":"REF: 905.213.0100 Instrument-Fix - Large 100 x 198 mm Unit: 100 pieces ",
         "refd":" REF: 905.214.0100 Instrument-Fix - X-Large 125 x 256 mm Unit: 100 pieces",
         name:"Sterile Barrier protector: Instrument-Fix",
         description:"Where ever the risk exist of sharp objects / instruments are damaging the sterile barrier the use of Instrument-Fix is advised. Fixating the instrument and covering the sharp edges by a highly puncture resistant material is reducing the risk of non-sterility of your operating instruments. The Instrument-Fix is coming in 4 standard sizes",
         file:"instrument-fix-small.pdf",
         image:"fortysix.png",
         characteristics:["✦ Produced from 200 gr/sqm paper and high puncture resistant resin",
         "✦ Suitable for steam sterilization processes ",
         "✦ Including a ISO 11140 Type 1 process Indicator for steam",
         "✦ Can be fully recycled.",
         "",
         "",]
         },
         {
         id:47,
         refa:"REF: 908.301.0250 Instrument Tray Corner 15 x 20 cm Unit: 250 pieces",
         name:"Sterile Barrier protector: Instrument Tray Corner",
         description:"The Sterintech™ Instrument Tray Corner is protecting the sterile barrier from the corners of the tray while transporting them. As such the corner of the tray (especially heavy trays) will not damage the sterile barrier any longer. They are designed for instrument trays of 5 cm or higher. The Instrument Tray Corners are coming unfolded but due to a clever design the folding into a corner is very easy",
         file:"instrument-tray-corner.pdf",
         image:"fortyseven.png",
         characteristics:["✦ Produced from 200 gr/sqm paper",
         "✦ Suitable for steam, EO and Formaldehyde sterilization processes.",
         "✦ Can be fully recycled",
         "",
         "",
         "",]
         },
          {
         id:48,
         refa:"REF: 901.101.1000 Container Filter round 19 cm central indicator Unit: 500 pieces  ",
         "refb":"REF: 901.102.1000 Container Filter round 19 cm indicator at lash Unit: 500 pieces",
         name:"Container Filter",
         description:"The Sterintech Container Filter is based upon both standards ISO 11607 and ISO 11140 and compliant to those standards. The used materials are mechanically strong to withstand the vacuum and steam pulse movements and are an effective biological barrier. Available in two versions:",
         file:"container-filter-fortyeight.pdf",
         image:"fortyeight.png",
         characteristics:["✦ Medical grade paper , 60 gram per square meter",
         "✦ In accordance with ISO 11607 - 1 : Hydrophobic, for containers",
         "✦ High mechanical strength and low liquid permeability ",
         "✦ Steam indicator conform to ISO 11140 - Type 1",
         "✦ Clear color transition of the indicator (Yellow - Dark)",
         " indicator (Yellow - Dark)",]
         },
           {
         id:49,
         refa:"REF: 901.001.0500 Container Filter round 19 cm central indicator Unit: 500 pieces  ",
         "refb":"REF: 901.002.0500 Container Filter round 19 cm indicator at lash Unit: 500 pieces",
         name:"Container Filter",
         description:"The Sterintech Container Filter is based upon both standards ISO 11607 and ISO 11140 and compliant to those standards. The used materials are mechanically strong to withstand the vacuum and steam pulse movements and are an effective biological barrier. Available in two versions: ",
         file:"container-filter-fortynine.pdf",
         image:"fortynine.png",
         characteristics:["✦ Medical grade paper , 60 gram per square meter",
         "✦ In accordance with ISO 11607 - 1 : Hydrophobic, for containers ",
         "✦ High mechanical strength and low liquid permeability",
         "✦ Steam indicator conform to ISO 11140 - Type 1",
         "✦ Clear color transition of the indicator (Yellow - Dark)",
         "✦ Contains no toxic materials",]
         },
            {
         id:50,
         refa:"REF: 903.101.0250 Container Card Unit: 250 pieces",
         name:"Container Card",
         description:"Container cards are an important aid to label and mark the container. Not only the content but also details like sterilization date, Expiry date , the person who packed the container can be written down on the card. The chemical process indicator is giving the indication whether it has been sterilized or not. The container card can be used for keeping records at the operating room when it is stored in the patient record",
         file:"container-card.pdf",
         image:"fifty.png",
         characteristics:["✦ Dimensions: 68 x 37,5 mm.",
         "✦ Suitable for steam sterilization processes",
         "✦ Can be fully recycled. ",
         "✦ Steam indicator conform to ISO 11140 - Type 1",
         "✦ Clear color transition of the indicator",
         "Other types and dimensions available upon request.",]
         },
             {
         id:51,
         refa:"REF: 903.103.1000 Container Card for Aesculap Unit: 1000 pieces ",
         "refb":"REF: 903.104.1000 Self-Adhesive Container Card for Aesculap Unit: 1000 pieces ",
         name:"Container Card (for Aesculap containers)",
         description:"Container cards are an important aid to label and mark the container. Not only the content but also details like sterilization date, Expiry date , the person who packed the container can be written down on the card. The chemical process indicator is giving the indication whether it has been sterilized or not. The container card can be used for keeping records at the operating room when it is stored in the patient record.",
         file:"container-card-aesculap.pdf",
         image:"fiftyone.png",
         characteristics:["✦ Dimensions: 74 x 35 mm.",
         "✦ Suitable for steam sterilization processes.",
         "✦ Can be fully recycled.",
         "✦ Steam indicator conform to ISO 11140 - Type 1",
         "✦ Clear color transition of the indicator to green",
         "Other types and dimensions available upon request.",]
         },
              {
         id:52,
         refa:"Ref: 703.059.1000 : Piggy Back Steam / EO label 70 x 40 mm, 70 x 50 mm, 70 x 35 mm, 50 x 40 mm",
         name:"Thermo-transfer printer indicator labels",
         description:"The Thermo-transfer printer labels are especially selected from raw material suppliers to suit the harsh environment conditions of steam sterilization. The selection was based upon requirements for the glue, the top material and ink printing conditions. ",
         file:"tt-label.pdf",
         image:"fiftytwo.png",
         characteristics:["★ Double chemical indicator , one for steam and one for Ethylene Oxide ",
         "★ Glue; Natural Rubber Latex free High stickiness ",
         "★ Compliant to REACH requirements ",
         "★ Free of any toxic particles",
         "★ Suitable for printing by Thermo-transfer printers",
         "★ Shelf-life : 3 years after production",]
         },
               {
         id:53,
         refa:"",
         name:"Thermo-transfer printer indicator labels",
         description:"Almost every Thermo-transfer printer indicator label is a customised product, manufactured to each customer’s specific needs",
         file:"tt-printer.pdf",
         image:"fiftythree.png",
         characteristics:["★ Single or double (piggy back) label material",
         "★ Tyvek, PP or Vellum top material ",
         "★ Indicators for STEAM, EO, FORM, Plasma",
         "★ Colored labels (incl. logo or Hospital address data)",
         "★ One, two or three part label",
         "★ On roll, folded or as sheets",]
         },
                {
         id:54,
         refa:"REF: 906.003.0050 Protein Rapid Swab Test Unit: 50 double swabs (100 tests)",
         name:"Protein Rapid Swab Test",
         description:"The EN-ISO-15883 standard is recommending a routine performance check of your washer disinfector. Rather then checking the cleanliness of your instruments visually you can easily test it by checking the level of proteins. The Protein Rapid Swab Test allows you to check the level of proteins left after washing disinfection on your instruments without any laboratory costs and within 5 seconds. The yellow swab will turn green when proteins are detected above 20 µg",
         file:"protein-rapid-swab-test.pdf",
         image:"fiftyfour.png",
         characteristics:["✦ Detects 20 µg of proteins, well below the required 100 µg as per EN ISO 15883",
         "✦ Easy to use, easy to interpret, no training required ",
         "✦ Very cost-effective in relation to laboratory tests",
         "✦ No guesswork anymore by visual check but knowing for sure Shelf-Life: 2 years after production date",
         "✦ Quick test results: less than 5 seconds",
         "✦ Non-toxic - safe to use - easy disposal.Calibrated test results ",]
         },
                 {
         id:55,
         refa:"REF: 905.101.0006 CSSD Marker, Blue Unit: 6 markers  ",
         "refb":"REF: 905.102.0006 CSSD Marker, Red Unit: 6 markers",
         "refc":" REF: 905.103.0006 CSSD Marker, Green Unit: 6 markers",
         "refd":"REF: 905.104.0006 CSSD Marker, Black Unit: 6 markers",
         name:"CSSD Markers",
         description:"The Sterintech™ CSSD Markers are very suitable to be used for CSSD applications. These non toxic markers are coming in four different colors and have a fine tip to create a clear writing possible on various substrates. The writings by these markings are not disappearing during any kind of sterilization method. ",
         file:"cssd-markers.pdf",
         image:"fiftyfive.png",
         characteristics:["✦ Available in 4 colors, permanent markers with pocket clip",
         "✦ Very fine point in order to create clear writings",
         "✦ No leaking, fast drying, water resistant",
         "✦ Not blurring during sterilization (depending of absorbance of paper)",
         "✦ Non-toxic - safe to use - easy disposal",
         "✦ Shelf-Life: 2 years after production date",]
         },
                  {
         id:56,
         refa:"REF:908.101.0030 Sticky Mat 1 45 x 115 cm Unit: 30 peel-able sheets ",
         "refb":"REF:908.101.0040 Sticky Mat 1 45 x 115 cm Unit: 40 peel-able sheets",
         "refc":"REF: 908.102.0030 Sticky Mat 2 65 x 115 cm Unit: 30 peel-able sheets ",
         "refd":" REF:908.103.0030 Sticky Mat 3 92 x 153 cm Unit: 30 peel-able sheets",
         name:"Sticky Mat",
         description:"Adhesive-coated contamination control mats or sticky mats are formulated and developed to meet the stringent cleanroom particulate specifications. Used on entryways, walkways, traffic areas where particle contamination is to be controlled. It is composed of easy to peel-off, disposable sticky mat layers that can effectively capture 99% all foot-borne and wheel-borne particulates from entering the controlled working environment. Each mat is composed of multiple layers of polyethylene films coated with custom high tack adhesive laminated together into a stack. ",
         file:"sticky-mat.pdf",
         image:"fiftysix.png",
         characteristics:["✦ Easy to peel to the next sheet by tags on one of the corners",
         "✦ Water-based acrylic adhesive with PH in between 7-8 ",
         "✦ Doesn't contain benzoic acid, 45 micron --> high stickiness",
         "✦ Certified RoHS, free from heavy metals and hazardous chemicals.",
         "✦ Shelf-Life: 5 years after production date",
         "",]
         },
                   {
         id:57,
         refa:"REF: 908.260.0100 Water Soluble bag, 20 mu, 66 x 84 cm, 60°C Unit: 4 x 25 bags ",
         name:"Water Soluble Laundry Bags",
         description:"The Water Soluble Laundry Bags are available for two temperatures and are suitable to collect, transport laundry in a safe way. They are dissolving during the washing process in less then 5 minutes completely. Available in one size only",
         file:"water-soluble-laundry-bags.pdf",
         image:"fiftyseven.png",
         characteristics:["✦ 20 mu quality makes the max. capacity up to 10 kilo of laundry",
         "✦ Water soluble at 60 degrees water",
         "✦ Biodegradable, Solvent resistant, Non-Toxic",
         "✦ Storage conditions: 10-30°C - 40-70% RH max",
         "✦ Shelf-Life: 3 years after production date",
         "",]
         },
                    {
         id:58,
         refa:"REF.: 908.400.0006 Pre-Cleaning Brush Set Unit: 6 different brushes ",
         name:" Pre-Cleaning Brush set",
         description:"A new arrival under the Sterintech™ product range for CSSD’s. A selected set of pre-cleaning brushes to assist to get rid of hard to remove spots and stains. All brushes can be thermally disinfected at 93 degrees Celsius. ",
         file:"brushes.pdf",
         image:"fiftyeight.png",
         characteristics:["✦ Instrument brush wide, white",
         "✦ Instrument brush rigid, green",
         "✦ Instrument brush extra rigid , blue",
         "✦ Tooth brush nylon , blue",
         "✦ Tooth brush metal , blue",
         "",]
         },
                     {
         id:59,
         refa:"",
         name:"Endoscope / Cannula Cleaning Brushes ",
         description:"A new expansion under the Sterintech™ product range for CSSD’s. A selected set of pre-cleaning brushes to assist to get rid of hard to remove spots and stains. Most brushes can be thermally disinfected at 93 degrees Celsius. For an overview of all brushes currently in our product range we kindly refer you to the next pages. Currently we offer a variety of Endoscope brushes, Cannula cleaning brushes, Pipe cleaner brushes and Instrument cleaning brushes. If there is another specific requirement from your side, please request us to add them to the range. ",
         file:"endoscope.pdf",
         image:"fiftynine.png",
         characteristics:["",
         "",
         "",
         "",
         "",
         "",]
         },
                      {
         id:60,
         refa:"",
         name:"Instrument marking tape on sheets ",
         description:"Especially selected and suitable for steam sterilization processes the Sterintech™ Instrument marking tapes provide a good stickiness to metal surfaces. A variety of designs is available to make the marking of instruments distinctive. For the designs and reference numbers , please refer to page two of this leaflet. Per sheet there are the following quantities and dimensions of strips available",
         file:"instrument-marking.pdf",
         image:"sixty.png",
         characteristics:["✦ Over 60 designs available (see page 2) ",
         "✦ Packed with 5 sheets together. ",
         "✦ Pinholes for easy storage of each sheet ",
         "✦ Strips are easy to pick from the sheet due to embossed cutting. ",
         "✦ Latex free glue / Non- Toxic ",
         "",]
         },
                       {
         id:61,
         refa:"REF: 903.001.0100 - White plastic Hang Tags (dimensions 50 x 236 mm, label area 50 x 90 mm)",
         "refb":"REF: 903.010.0500 - Red self-adhesive plastic labels 70 x 35 mm ",
         "refc":"REF: 903.011.0500 - Green self-adhesive plastic labels 70 x 35 mm",
         "refd":"  REF: 903.012.0500 - Blue self-adhesive plastic labels 70 x 35 mm ",
         "refe":"REF: 903.013.0500 - Yellow self-adhesive plastic labels 70 x 35 mm ",
         name:"Instrument tray/container Hang Tags ",
         description:"The instrument tray/container Hang Tags are an excellent aid to mark instrument trays during their transportation from the OR back to the CSSD in case of lost / damaged instruments but also when stored at the CSSD and transported to the OR to indicate what set the container contains, what department it should go and / or to make any remark in between departments specifically for that one set or container. Available are :",
         file:"instrument-tray.pdf",
         image:"sixtyone.png",
         characteristics:["✦ Flexible in design / usage / message (see second page for graphics) ",
         "✦ Can be printed by barcode printer or written on by CSSD Marker",
         "✦ 4 different colors of labels ",
         "✦ Latex free glue / Non-Toxic ",
         "",
         "",]
         },
           {
         id:62,
         refa:"REF: 906.005.0025 - UltraSon - Ultrasonic Bath Efficiency Test - 25 vials per unit",
         name:"UltraSon - Efficiency Test",
         description:"The Ultrasonic baths in use at the Pre-cleaning side of the CSSD, needs to be tested on a regular basis. The UltraSon - Ultrasonic Bath Efficiency Test can be used for validation purposes as well as routine process testing. Once placed in the Ultrasonic bath (in accordance with the IFU) the color of the UltraSon Test is shifting from blue into yellow if the energy levels of the Ultrasonic bath are ok. At high levels of energy the UltraSon can even color into a white color fluid.",
         file:"ultrason.pdf",
         image:"sixtytwo.png",
         characteristics:["✦ Easy to use - Easy to interpret",
         "✦ Can be used for validation purposes ",
         "✦ Can be used for routine process testing",
         "✦ Non-Toxic",
         "",
         "",]
         },
                        
]