# Generated by Django 5.2 on 2025-05-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="products/pdfs/"),
        ),
    ]
